{% set name = "safe-netrc" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1dcc7263b4d9ce72e0109d8e2bc9ba89c8056ccc618d26c8c94802c6fd753720

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=61
    - setuptools-scm >=6.2
  run:
    - python >=3.7

test:
  imports:
    - safe_netrc
  requires:
    - pip
    - pytest
  commands:
    # check requirements
    - python -m pip check
    - python -m pip show safe-netrc
    # run test suite
    - python -m pytest -v -rs --pyargs safe_netrc.tests

about:
  home: https://git.ligo.org/computing/software/safe-netrc
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  summary: Safe netrc file parser
  description: This package provides a subclass of the Python standard library netrc.netrc class to add some custom behaviors.

extra:
  recipe-maintainers:
    - duncanmmacleod
