{% set name = "safe-netrc" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 55fe78dfc8bda48ee5b26c930a8efdecbb7ff5b5a45e2552381c84f13bb4a98a

build:
  noarch: "python"
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools >=30.3.0
  run:
    - python

test:
  imports:
    - safe_netrc
  requires:
    - pytest
  commands:
    - python -m pytest -v -rs --pyargs safe_netrc.tests

about:
  home: "https://git.ligo.org/emfollow/safe-netrc"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: "Safe netrc file parser"
  description: "This package provides a subclass of the Python standard library netrc.netrc class to add some custom behaviors."

extra:
  recipe-maintainers:
    - duncanmmacleod
