appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: VX+0FHIL/ah64jZ3p+e0JOmCDl6POMqhrwiT1yY67UFpdpn4QZ5uVNs/0HWinYR6HTd+bR3K1fQKyxNRnTdDXMeb5jIIN1BOeTEcJOfuYzNzTIx6arllbqeYMslxJUvRDfcEnFfNrCO1MLYYWWGc/ZbvulFutPjW1BCBGfgVvTfpNLcG0eUOtDvkPPwj+zdy98/hfx6vmKcV9Hs5D7SQ1Y+wKjh098c5DiuMEaxP3FzUGnloU6eQ3SZLT/zKtblDNJj3OVbzrIBxHByYOI5iRDHngzK6C3vIJ4GBCzOZQOUALtT+S4mXf6m4docwtX5q9pgOzRqUGNXx6/4I2aQFSmc2xTeKdxBLgHZq4Ezkr0UcIfFpKaNQRLzfn1QarbTtbev4F9VWRX0ECJHxeZIDvs0yKK+dq1NVQILqJwHGrPmMJEuyPVfm/AMtd03fcq/PYuLBF+z53KS0BeZ1HecATiR93kL/0OCHvePclvwbTMm/jXQXHTD5TVW/E/HdrX2f2mGd9xCLPGah6sIR8NErJSyQqP1mRfubGssKvvc/GS5L8iPt0WfFCJRBuaVGVSQU4+EOhcw3cSbMEuE5816YBQuF7FZa0E8OzJMag4Rp4sR5Lm6HmqT3MciJncidRRjyxLRlN/g7EeMNWbaa6jlpuw1p+hwxMNt+BG7FjTXhf+w=}
conda_forge_output_validation: false
